let editing=null;const $=s=>document.querySelector(s);function toast(m){const t=$('#toast');t.textContent=m;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2200)}
function stats(){const d=getData();$('#statProducts').textContent=d.products.length;$('#statStock').textContent=d.products.reduce((a,p)=>a+Number(p.stock||0),0);$('#statMenus').textContent=d.menus.length}
function productsAdmin(){const d=getData();$('#adminProducts').innerHTML=d.products.map(p=>`<tr><td><img src="${esc(p.image)}" alt=""></td><td><b>${esc(p.name)}</b><br><small>${p.id}</small></td><td>${esc(p.category)}</td><td>${money(p.price)}</td><td>${p.stock}</td><td class="admin-actions"><button class="btn btn-outline" onclick="editProduct('${p.id}')">Editar</button><button class="btn btn-outline danger" onclick="removeProduct('${p.id}')">Quitar</button></td></tr>`).join('');stats()}
function menusAdmin(){const d=getData();$('#menuRows').innerHTML=d.menus.map((m,i)=>`<tr><td>${esc(m.label)}</td><td>${esc(m.href)}</td><td><button class="btn btn-outline danger" onclick="removeMenu(${i})">Quitar</button></td></tr>`).join('');stats()}
window.editProduct=id=>{const p=getData().products.find(x=>x.id===id);editing=id;for(const k of ['name','category','description','formats','price','stock','image'])$('#p_'+k).value=Array.isArray(p[k])?p[k].join(', '):p[k]??'';$('#productTitle').textContent='Editar producto';scrollTo({top:0,behavior:'smooth'})};
window.removeProduct=id=>{if(!confirm('¿Quitar este producto?'))return;const d=getData();d.products=d.products.filter(p=>p.id!==id);saveData(d);productsAdmin();toast('Producto quitado')};
window.removeMenu=i=>{const d=getData();d.menus.splice(i,1);saveData(d);menusAdmin();toast('Menú quitado')};
function resetForm(){editing=null;$('#productForm').reset();$('#productTitle').textContent='Nuevo producto'}
document.addEventListener('DOMContentLoaded',()=>{productsAdmin();menusAdmin();$('#productForm').addEventListener('submit',e=>{e.preventDefault();const d=getData(),v=k=>$('#p_'+k).value.trim();const p={id:editing||`ARF-${Date.now()}`,name:v('name'),category:v('category'),description:v('description'),formats:v('formats').split(',').map(x=>x.trim()).filter(Boolean),price:Number(v('price')||0),stock:Number(v('stock')||0),image:v('image')||'assets/productos/producto-001.jpg',featured:true};if(editing)d.products[d.products.findIndex(x=>x.id===editing)]=p;else d.products.unshift(p);saveData(d);resetForm();productsAdmin();toast('Producto guardado')});$('#cancelEdit').onclick=resetForm;$('#menuForm').addEventListener('submit',e=>{e.preventDefault();const d=getData();d.menus.push({label:$('#m_label').value.trim(),href:$('#m_href').value.trim()});saveData(d);e.target.reset();menusAdmin();toast('Menú agregado')});$('#exportBtn').onclick=()=>{const payload='window.ARFLO_INITIAL_DATA = '+JSON.stringify(getData(),null,2)+';\n';const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([payload],{type:'text/javascript'}));a.download='catalog-data.js';a.click();URL.revokeObjectURL(a.href);toast('Catálogo exportado')};$('#importFile').onchange=e=>{const f=e.target.files[0];if(!f)return;const r=new FileReader();r.onload=()=>{try{const raw=r.result.replace(/^\s*window\.ARFLO_INITIAL_DATA\s*=\s*/,'').replace(/;\s*$/,'');saveData(JSON.parse(raw));productsAdmin();menusAdmin();toast('Datos importados')}catch{alert('Archivo no válido')}};r.readAsText(f)};$('#restoreBtn').onclick=()=>{if(confirm('¿Restaurar el catálogo original?')){localStorage.removeItem(KEY);productsAdmin();menusAdmin();toast('Catálogo restaurado')}}});
